project:
  type: website

website:
  title: ""
  site-url: https://nationalwomenssoccerleague.com
  resources:
    - CNAME


format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: article   


