project:
  type: website

website:
  title: ""


format:
  html:
    include-in-header:
      text: '<meta name="viewport" content="width=device-width, initial-scale=1.0">
    theme: lux
    css: styles.css
    toc: true    



